### PR TITLE
Supervise

### PR DESCRIPTION
**Pull request by dkappe**
Modifications to reenable  —supervise flag and also accept FEN headers. Tested as working with current training setup.

### CODE REVIEW

**Comment by killerducky** [comment]
Why FEN headers? Things might go weird if the pgns have arbitrary FENs with no history. I guess maybe supporting them is ok in a "user beware" sort of way?

Please make GAMES_PER_CHUNK a constexpr instead of define. See Network.cpp for examples.

Please delete the comments around the "Need to update SL flow" part.

**Comment by dkappe** [comment]
Changed define to constexpr. The comments north of the SL flow are still relevant, i.e. lczero probably doesn't need to load a network and it's still a TODO. Left those comments. Next fix is probably breaking out the whole supervised data functionality into a separate command.

**Comment by killerducky** [comment]
I changed it to master because that's what the formal process is: New development on master. Stable code in release. git clone defaults to release. 

But this entire repo is basically deprecated so I don't know if we need such a process. Also this change shouldn't do anything(?) to normal client/engine usage. I'm just going to think maybe 1 day on this. Ping me again tomorrow if I didn't do anything yet.

**Comment by killerducky** [comment]
I will merge to master. Merging to release implies some extra QA which I'm not willing to do for now.

**Comment by dkappe** [comment]
Woohoo!! Does this mean I get developer colors in Discord. ;-)

**Pull request merged**
